version: '3.3'
services:
  backend:
    container_name: backend
    build: ./simple-api
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - "8081:8080"

  backend2:
    container_name: backend2
    build: ./simple-api
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - "8082:8080"

  database:
    container_name: database
    restart: always
    build: ./database
    networks:
      - app-network
    env_file:
      - database/.env

  httpd:
    container_name: reverse_proxy
    build: ./httpd
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
      - backend2


volumes:
  my_db_volume:
    driver: local

networks:
  app-network:


