all:
 vars:
   ansible_user: centos
   ansible_ssh_private_key_file: ../../id_rsa
   docker_username: mquelennec
   docker_password: wzyRzZ5169780
 children:
   prod:
     hosts: morgane.quelennec.takima.cloud
